# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      NODE_ENV: development
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: cicdtest
      DB_USER: myusername
      DB_PASS: mypassword
      PORT: 3000

    steps:
      - uses: actions/checkout@v7

      - name: Setup Node build
        uses: ./.github/actions/setup-node-build
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MySQL service
        run: sudo systemctl start mysql

      - name: Run database creation script from the repo
        run: mysql -u root -proot < db/create-db.sql

      - name: Run tests
        run: npm run test

  apidoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node build
        uses: ./.github/actions/setup-node-build

      - name: Generate API documentation
        run: npm run apidoc

      - name: Upload API documentation artifact
        uses: actions/upload-artifact@v7
        with:
          name: api-docs
          path: docs
